[2021.12.16/13:47:31] - Traceback (most recent call last):
  File "test.py", line 24, in <module>
    df=pd.read_csv('1123_test_copy.csv')
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\io\parsers.py", line 1368, in _open_handles
    storage_options=kwds.get("storage_options", None),
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\io\common.py", line 647, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '1123_test_copy.csv'

[2021.12.16/13:47:37] - Traceback (most recent call last):
  File "test.py", line 24, in <module>
    df=pd.read_csv('1123_test_copy.csv')
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\io\parsers.py", line 1368, in _open_handles
    storage_options=kwds.get("storage_options", None),
  File "C:\Users\ASC\anaconda3\envs\py37\lib\site-packages\pandas\io\common.py", line 647, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '1123_test_copy.csv'

