[2021.12.16/14:48:50] - Traceback (most recent call last):
  File "test.py", line 47, in <module>
    df=test()
  File "test.py", line 42, in test
    err = err+e
UnboundLocalError: local variable 'e' referenced before assignment

